# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

cache: packages

addons:
  apt:
    packages:
    - tcl8.6-dev
    - tk8.6-dev

r_binary_packages:
  - ggplot2
  - tidyr
  - dplyr
  - magrittr
  - knitr
  - rmarkdown
  - testthat
  - DEoptimR
  - nloptr
  - sm