#' Competition measurments
#' 
#' A dataset containing estimated parameters for the competition dataset
#' The dataset is generated by the code of the vignette \code{Multi-species parameter optimization}.
#' It is structured as a nested list with three levels, of the form:
#' param_estimates[[species]][[fecundity model]][[optimization method]]
#' In the provided dataset, we include models 3, 4, and 5, and optimization method ..XXX..
#' For each combination of these three factors, all model parameters are given. If a parameter is not estimated
#' (e.g. upper/lower errors), the value stored is NA.
#' 
#' \itemize{          
#'   \item lambda: per germinant fecundity
#'   \item lambda.lower.error: 
#'   \item lambda.upper.error:
#'   \item sigma:
#'   \item alpha: effect of every competitor species on the focal species
#'   \item alpha.lower.error: 
#'   \item alpha.upper.error:
#'   \item lambda.cov: effect of every covariate on lambda
#'   \item lambda.cov.lower.error: 
#'   \item lambda.cov.upper.error:
#'   \item alpha.cov: effect of every covariate on alpha
#'   \item alpha.cov.lower.error: 
#'   \item alpha.cov.upper.error:
#'   \item log.likelihood: log-likelihood of the fitted parameters and model
#'   }
#'   
#' @note For details, see vignette \code{Multi-species parameter optimization}
#' @docType data
#' @keywords datasets
#' @name param_estimates
#' @usage data(param_estimates)
#' @format A nested list with three levels
"param_estimates"